import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

export interface ReportData {
  username: string
  period: string
  total: number
  delta: number
  entries: Array<{
    logged_at: string
    category: string
    description: string
    co2_kg: number
  }>
  categoryTotals: Array<{ label: string; value: number; pct: number }>
  monthlyData: Array<{ month: string; total: number }>
  insights: string[]
  challenges?: Array<{ title: string; progress: number; saving: string }>
  householdData?: Array<{ memberName: string; role: string; total: number }>
  includeSections?: Set<string>
}

// ─── Colour palette ──────────────────────────────────────────────────────────
const C = {
  darkBg:     [15, 22, 18]   as [number, number, number],
  green:      [34, 197, 94]  as [number, number, number],
  greenDim:   [22, 130, 62]  as [number, number, number],
  white:      [240, 253, 244] as [number, number, number],
  black:      [20,  20,  20]  as [number, number, number],
  grey:       [100, 100, 100] as [number, number, number],
  lightGrey:  [230, 230, 230] as [number, number, number],
  bgCard:     [245, 250, 247] as [number, number, number],
}

// ─── Helpers ─────────────────────────────────────────────────────────────────
const PAGE_W = 210
const PAGE_H = 297
const MARGIN = 15

function drawHeader(doc: jsPDF, period: string, username: string) {
  doc.setFillColor(...C.darkBg)
  doc.rect(0, 0, PAGE_W, 38, "F")

  // Leaf icon simulation – small circle
  doc.setFillColor(...C.green)
  doc.circle(MARGIN + 3, 14, 3, "F")

  doc.setTextColor(...C.white)
  doc.setFontSize(9)
  doc.setFont("helvetica", "bold")
  doc.text("CarbonLedger", MARGIN + 9, 15.5)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.text("Your Planet. Your Numbers. Your Move.", MARGIN + 9, 21)

  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text(`Personal Carbon Report — ${period}`, MARGIN, 32)

  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text(username, PAGE_W - MARGIN, 32, { align: "right" })
}

function drawFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const y = PAGE_H - 8
  doc.setDrawColor(...C.lightGrey)
  doc.setLineWidth(0.3)
  doc.line(MARGIN, y - 3, PAGE_W - MARGIN, y - 3)

  doc.setFontSize(7)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(...C.grey)
  doc.text("Generated by CarbonLedger", MARGIN, y)
  doc.text(
    new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }),
    PAGE_W / 2, y, { align: "center" }
  )
  doc.text(`Page ${pageNum} / ${totalPages}`, PAGE_W - MARGIN, y, { align: "right" })
}

function sectionTitle(doc: jsPDF, label: string, y: number): number {
  doc.setFontSize(8)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(...C.green)
  doc.text(label.toUpperCase(), MARGIN, y)

  doc.setDrawColor(...C.green)
  doc.setLineWidth(0.4)
  doc.line(MARGIN, y + 1.5, PAGE_W - MARGIN, y + 1.5)

  return y + 7
}

// ─── Main export ─────────────────────────────────────────────────────────────
export const generatePDF = (data: ReportData): void => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })

  // ══════════════════════════════════════════════════════
  // PAGE 1 — Cover + Summary + Category Breakdown
  // ══════════════════════════════════════════════════════
  drawHeader(doc, data.period, data.username)

  let y = 48

  // ── Summary box ────────────────────────────────────────
  y = sectionTitle(doc, "Summary", y)

  doc.setFillColor(...C.bgCard)
  doc.roundedRect(MARGIN, y, PAGE_W - MARGIN * 2, 32, 3, 3, "F")

  doc.setFontSize(30)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(...C.green)
  doc.text(`${Math.round(data.total)} kg CO₂`, MARGIN + 6, y + 14)

  const deltaText = data.delta > 0 ? `▲ +${data.delta}%` : data.delta < 0 ? `▼ ${data.delta}%` : "─ 0%"
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(...C.grey)
  doc.text(`${deltaText} vs previous period`, MARGIN + 6, y + 21)

  const status = data.total < 350 ? "✓ On Track" : "⚠ Over Target"
  doc.setFontSize(9)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(data.total < 350 ? C.green[0] : 220, data.total < 350 ? C.green[1] : 100, data.total < 350 ? C.green[2] : 20)
  doc.text(status, MARGIN + 6, y + 28)

  // Right-side key stats
  const target = 350
  const pctUsed = Math.min(100, Math.round((data.total / target) * 100))
  doc.setFontSize(8)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(...C.grey)
  doc.text(`Monthly Target: ${target} kg`, PAGE_W - MARGIN - 55, y + 10)
  doc.text(`Used: ${pctUsed}% of target`, PAGE_W - MARGIN - 55, y + 16)
  doc.text(`Entries: ${data.entries.length}`, PAGE_W - MARGIN - 55, y + 22)
  doc.text(`Avg / day: ${data.entries.length > 0 ? (data.total / 30).toFixed(1) : "0"} kg`, PAGE_W - MARGIN - 55, y + 28)

  y += 38

  // ── Category Breakdown ─────────────────────────────────
  if (!data.includeSections || data.includeSections.has("Category breakdown")) {
    y = sectionTitle(doc, "Category Breakdown", y)

    const catColors: Record<string, [number, number, number]> = {
      Food:      [34,  197, 94],
      Transport: [59,  130, 246],
      Energy:    [251, 191, 36],
      Shopping:  [167, 139, 250],
    }

    data.categoryTotals.forEach((cat) => {
      const color = catColors[cat.label] || C.green

      doc.setFont("helvetica", "normal")
      doc.setFontSize(9)
      doc.setTextColor(...C.black)
      doc.text(cat.label, MARGIN, y)
      doc.text(`${cat.value.toFixed(1)} kg`, 80, y)
      doc.text(`${cat.pct}%`, 110, y)

      // Progress bar
      const barX = 125
      const barW = 55
      doc.setFillColor(...C.lightGrey)
      doc.roundedRect(barX, y - 3.5, barW, 4, 1, 1, "F")
      doc.setFillColor(...color)
      doc.roundedRect(barX, y - 3.5, Math.max(1, (cat.pct / 100) * barW), 4, 1, 1, "F")

      y += 8
    })
    y += 4
  }

  // ── Daily Activity Heatmap (28-day grid) ──────────────
  if (!data.includeSections || data.includeSections.has("Daily heatmap")) {
    if (y + 30 > PAGE_H - 20) { doc.addPage(); drawHeader(doc, data.period, data.username); y = 48 }
    y = sectionTitle(doc, "28-Day Activity Heatmap", y)

    const dateMap: Record<string, number> = {}
    data.entries.forEach(e => {
      const day = e.logged_at.slice(0, 10)
      dateMap[day] = (dateMap[day] || 0) + (e.co2_kg || 0)
    })
    const maxDaily = Math.max(...Object.values(dateMap), 1)

    const cellSize = 6
    const gap = 1.5
    const cols = 7
    const rows = 4

    // Day-of-week labels
    const days = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"]
    doc.setFontSize(6)
    doc.setTextColor(...C.grey)
    days.forEach((d, i) => {
      doc.text(d, MARGIN + i * (cellSize + gap) + cellSize / 2 - 1.5, y)
    })
    y += 4

    for (let row = 0; row < rows; row++) {
      for (let col = 0; col < cols; col++) {
        const idx = row * cols + col
        const date = new Date()
        date.setDate(date.getDate() - (27 - idx))
        const key = date.toISOString().slice(0, 10)
        const val = dateMap[key] || 0
        const intensity = val / maxDaily

        const r = Math.round(C.bgCard[0] + (C.green[0] - C.bgCard[0]) * intensity)
        const g = Math.round(C.bgCard[1] + (C.green[1] - C.bgCard[1]) * intensity)
        const b = Math.round(C.bgCard[2] + (C.green[2] - C.bgCard[2]) * intensity)

        doc.setFillColor(r, g, b)
        doc.roundedRect(MARGIN + col * (cellSize + gap), y + row * (cellSize + gap), cellSize, cellSize, 1, 1, "F")
      }
    }
    y += rows * (cellSize + gap) + 8
  }

  // ══════════════════════════════════════════════════════
  // PAGE 2 — Monthly Trend + Recent Entries Table
  // ══════════════════════════════════════════════════════
  doc.addPage()
  drawHeader(doc, data.period, data.username)
  y = 48

  // ── Monthly Trend ──────────────────────────────────────
  y = sectionTitle(doc, "Monthly Trend (Last 6 Months)", y)

  if (data.monthlyData && data.monthlyData.length > 0) {
    const maxMonthly = Math.max(...data.monthlyData.map(m => m.total), 1)
    const maxBarW = PAGE_W - MARGIN * 2 - 50

    data.monthlyData.forEach((m) => {
      const barW = Math.max(1, (m.total / maxMonthly) * maxBarW)
      doc.setFontSize(8)
      doc.setFont("helvetica", "normal")
      doc.setTextColor(...C.black)
      doc.text(m.month, MARGIN, y)

      doc.setFillColor(...C.bgCard)
      doc.roundedRect(MARGIN + 16, y - 3.5, maxBarW, 4.5, 1, 1, "F")
      doc.setFillColor(...C.green)
      doc.roundedRect(MARGIN + 16, y - 3.5, barW, 4.5, 1, 1, "F")

      doc.setFontSize(8)
      doc.setTextColor(...C.grey)
      doc.text(`${Math.round(m.total)} kg`, PAGE_W - MARGIN, y, { align: "right" })

      y += 9
    })
  } else {
    doc.setFontSize(8)
    doc.setTextColor(...C.grey)
    doc.text("No monthly data available", MARGIN, y)
    y += 10
  }

  y += 6

  // ── Recent Entries Table ───────────────────────────────
  y = sectionTitle(doc, "Logged Entries", y)

  if (data.entries && data.entries.length > 0) {
    const tableRows = data.entries.slice(0, 20).map(e => [
      new Date(e.logged_at).toLocaleDateString("en-US", { month: "short", day: "numeric" }),
      e.category.charAt(0).toUpperCase() + e.category.slice(1),
      e.description || "—",
      `${(e.co2_kg || 0).toFixed(2)} kg`,
    ])

    autoTable(doc, {
      startY: y,
      head: [["Date", "Category", "Description", "CO₂"]],
      body: tableRows,
      theme: "grid",
      headStyles: {
        fillColor: C.darkBg,
        textColor: C.white,
        fontSize: 8,
        fontStyle: "bold",
        halign: "left",
      },
      bodyStyles: {
        fontSize: 7.5,
        textColor: C.black,
      },
      alternateRowStyles: {
        fillColor: C.bgCard,
      },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { cellWidth: 28 },
        2: { cellWidth: 110 },
        3: { cellWidth: 20, halign: "right" },
      },
      margin: { left: MARGIN, right: MARGIN },
    })
  } else {
    doc.setFontSize(8)
    doc.setTextColor(...C.grey)
    doc.text("No entries logged for this period.", MARGIN, y)
  }

  // ══════════════════════════════════════════════════════
  // PAGE 3 — AI Insights + Challenges
  // ══════════════════════════════════════════════════════
  doc.addPage()
  drawHeader(doc, data.period, data.username)
  y = 48

  // ── AI Insights ────────────────────────────────────────
  if (!data.includeSections || data.includeSections.has("AI insights")) {
    y = sectionTitle(doc, "AI Insights", y)

    if (data.insights && data.insights.length > 0) {
      data.insights.forEach((insight, i) => {
        if (y + 20 > PAGE_H - 20) return // guard

        // Insight card
        doc.setFillColor(...C.bgCard)
        const insightLines = doc.splitTextToSize(insight, PAGE_W - MARGIN * 2 - 16)
        const cardH = insightLines.length * 5 + 10
        doc.roundedRect(MARGIN, y, PAGE_W - MARGIN * 2, cardH, 3, 3, "F")

        // Green left accent bar
        doc.setFillColor(...C.green)
        doc.roundedRect(MARGIN, y, 3, cardH, 1, 1, "F")

        doc.setFontSize(8)
        doc.setFont("helvetica", "bold")
        doc.setTextColor(...C.green)
        doc.text(`Insight ${i + 1}`, MARGIN + 7, y + 6)

        doc.setFont("helvetica", "normal")
        doc.setTextColor(...C.black)
        doc.setFontSize(8)
        doc.text(insightLines, MARGIN + 7, y + 12)

        y += cardH + 5
      })
    } else {
      doc.setFontSize(8)
      doc.setTextColor(...C.grey)
      doc.text("No AI insights available for this period.", MARGIN, y)
      y += 10
    }

    y += 4
  }

  // ── Challenges ─────────────────────────────────────────
  if (data.challenges && data.challenges.length > 0 &&
      (!data.includeSections || data.includeSections.has("Challenges"))) {
    y = sectionTitle(doc, "Active Challenges", y)

    data.challenges.forEach((ch) => {
      if (y + 22 > PAGE_H - 20) return

      doc.setFillColor(...C.bgCard)
      doc.roundedRect(MARGIN, y, PAGE_W - MARGIN * 2, 18, 3, 3, "F")

      doc.setFontSize(9)
      doc.setFont("helvetica", "bold")
      doc.setTextColor(...C.black)
      doc.text(ch.title, MARGIN + 5, y + 6)

      doc.setFontSize(8)
      doc.setFont("helvetica", "normal")
      doc.setTextColor(...C.grey)
      doc.text(`Saving: ${ch.saving}`, MARGIN + 5, y + 12)

      // Progress bar
      const barX = PAGE_W - MARGIN - 65
      const barW = 60
      doc.setFillColor(...C.lightGrey)
      doc.roundedRect(barX, y + 5, barW, 4, 1, 1, "F")
      doc.setFillColor(...C.green)
      doc.roundedRect(barX, y + 5, Math.max(1, (ch.progress / 100) * barW), 4, 1, 1, "F")

      doc.setFontSize(7)
      doc.setTextColor(...C.green)
      doc.text(`${ch.progress}%`, barX + barW + 2, y + 9)

      y += 22
    })
  }

  // ── Household Data ─────────────────────────────────────────
  if (data.householdData && data.householdData.length > 0 &&
      (!data.includeSections || data.includeSections.has("Household data"))) {
    
    if (y + 30 > PAGE_H - 20) { doc.addPage(); drawHeader(doc, data.period, data.username); y = 48 }
    y = sectionTitle(doc, "Household Emissions", y)

    const maxHTotal = Math.max(...data.householdData.map(m => m.total), 1)
    const maxBarW = PAGE_W - MARGIN * 2 - 80

    data.householdData.forEach((m) => {
      if (y + 12 > PAGE_H - 20) { doc.addPage(); drawHeader(doc, data.period, data.username); y = 48 }

      doc.setFontSize(9)
      doc.setFont("helvetica", "bold")
      doc.setTextColor(...C.black)
      doc.text(m.memberName, MARGIN, y)

      doc.setFont("helvetica", "normal")
      doc.setFontSize(7)
      doc.setTextColor(...C.grey)
      doc.text(`(${m.role})`, MARGIN, y + 4)

      // Progress bar
      doc.setFillColor(...C.bgCard)
      doc.roundedRect(MARGIN + 35, y - 3.5, maxBarW, 4.5, 1, 1, "F")
      
      const barW = Math.max(1, (m.total / maxHTotal) * maxBarW)
      doc.setFillColor(...C.green)
      doc.roundedRect(MARGIN + 35, y - 3.5, barW, 4.5, 1, 1, "F")

      doc.setFontSize(8)
      doc.setTextColor(...C.black)
      doc.text(`${Math.round(m.total)} kg`, PAGE_W - MARGIN, y, { align: "right" })

      y += 12
    })
    y += 5
  }

  // ── Footer on all pages ───────────────────────────────
  const totalPages = (doc as any).internal.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    drawFooter(doc, p, totalPages)
  }

  // ── Save ──────────────────────────────────────────────
  const safePeriod = data.period.replace(/\s+/g, "_")
  doc.save(`CarbonLedger_Report_${safePeriod}.pdf`)
}
